os: windows
language: shell
cache:
  directories:
    - mydir
script:
  - ls -la / C:/
  - ls -la mydir
  - grep -rne . mydir/ || echo no files found
  - date -R > mydir/out.txt
  - ls -la mydir
notifications:
  email: false
