os: windows
language: shell
cache:
  directories:
    - mydir
script:
  - env
  - ls -laR ~/.casher
  - cat ~/.casher/fetch.log
  - cat ~/.casher/fetch.err.log
  - for i in ~/.casher/*.tgz; do tar tvf "$i"; done
  - ls -la / C:/
  - ls -la mydir
  - grep -rne . mydir/ || echo no files found
  - date -R > mydir/out.txt
  - ls -la mydir
notifications:
  email: false
