os: windows
language: shell
script:
  - choco list --localonly
  - choco install strawberryperl
  - |
    # Apply Process paths before Machine to ensure /bin appears before others.
    export PATH="$(powershell -Command '("Process", "Machine" | % {
      [Environment]::GetEnvironmentVariable("PATH", $_) -Split ";" -Replace "\\$", ""
    } | Select -Unique | % { cygpath $_ }) -Join ":"')"
    echo "PATH=$PATH"
  - ls -la C:/Perl/bin C:/Strawberry/perl/bin || true
  - (mkdir build1 && cd build1 && cmake -A x64 --trace-expand ..)
  - (mkdir build2 && cd build2 && cmake -A x64 --trace ..)
notifications:
  email: false
