os: windows
language: shell
cache:
  # Fix absolute extraction - https://github.com/travis-ci/casher/pull/38
  branch: 46c41ee208def16781fe4075283b70e1dbfe70ae
  directories:
    - C:/mydir
script:
  - cat ~/build.sh
  - env
  - ls -laR ~/.casher
  - cat fetch.log
  - cat fetch.err.log
  - for i in ~/.casher/*.t?z; do tar tvf "$i"; done
  - cat ~/.casher/bin/casher
  - ls -laR ~
  - ls -la / C:/
  - ls -la C:/mydir
  - grep -rne . C:/mydir/ || echo no files found
  - date -R > C:/mydir/two.txt
  - ls -la C:/mydir
after_script:
  - find ~ . -name '*.t?z' -ls -exec tar tvf {} \;
  - find . -name '*.log' -ls -exec cat {} \;
notifications:
  email: false
